[project]
name = "python-project-template"
version = "0.1.0"
description = "Template for personel python projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
